{{- if .Values.api.enabled }}
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "api"
  namespace: {{ .Values.global.namespace }}
  labels:
    app: "api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
      - name: "api"
        image: local/log-demo
        imagePullPolicy: Never
{{- end }}