apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: api